spring.application.name=board-backend
server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/whiteflow_boards}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.tomcat.max-http-form-post-size=100MB
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
# spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_SHOW_SQL:true}
